//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Enigma_Buri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaleBmi
    {
        public string Age_group { get; set; }
        public string Gender { get; set; }
        public int Year { get; set; }
        public string Underweight { get; set; }
        public string Normal_range_i { get; set; }
        public string Normal_range_ii { get; set; }
        public string Total_normal_range { get; set; }
        public string Overweight { get; set; }
        public string Obesity_class_i { get; set; }
        public string Obesity_class_ii { get; set; }
        public string Obesity_class_iii { get; set; }
        public string Total_obese { get; set; }
        public string Total_overweight_and_obese { get; set; }
    }
}
